export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const FETCH_CHANNELS = "CREATE_CHANNELS";
export const FETCH_CHANNEL = "CREATE_CHANNEL";
export const EDIT_CHANNEL = "EDIT_CHANNEL";
export const DELETE_CHANNEL = "DELETE_CHANNEL";
export const SELECT_CHANNEL = "SELECT_CHANNEL";
