export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const CREATE_CHANNEL = "CREATE_CHANNEL";
export const FETCH_CHANNELS = "CREATE_CHANNELS";
export const FETCH_CHANNEL = "CREATE_CHANNEL";
export const EDIT_CHANNEL = "EDIT_CHANNEL";
export const DELETE_CHANNEL = "DELETE_CHANNEL";
export const SELECT_CHANNEL = "SELECT_CHANNEL";
export const FLUSH_CHANNELS = "FLUSH_CHANNELS";

export const messagesTypes = {
	FETCH_MESSAGES: "FETCH_MESSAGES",
	POST_MESSAGE: "POST_MESSAGE",
};

export const usersTypes = {
	REGISTER_USER: "REGISTER_USER",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT_USER: "LOGOUT_USER",
	UNAUTHORIZED: "UNAUTHORIZED",
};

export const komuTypes = {
	CREATE_KOMU: "CREATE_KOMU",
	JOIN_KOMU: "JOIN_KOMU",
	USER_ALREADY_IN_KOMU: "USER_ALREADY_IN_KOMU",
	LIST_USER_KOMUS: "LIST_USER_KOMUS",
	SELECT_KOMU: "SELECT_KOMU",
};

export const calendarTypes = {
	CREATE_EVENT: "CREATE_EVENT",
	GET_EVENTS: "GET_EVENTS",
	GET_EVENT: "GET_EVENT",
	EDIT_EVENT: "EDIT_EVENT",
	DELETE_EVENT: "DELETE_EVENT",
};
